In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('voice-classification.csv')

In [3]:
df.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
 20  label     3168 non-null   obje

# Lets pickup the IV and DV

In [5]:
X = df.iloc[:,0:-1]
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
dtypes: float64(20)
memory usage: 4

In [6]:
y = df.iloc[:, -1]
y

0         male
1         male
2         male
3         male
4         male
         ...  
3163    female
3164    female
3165    female
3166    female
3167    female
Name: label, Length: 3168, dtype: object

In [7]:
from sklearn.preprocessing import LabelEncoder
gender_encoder = LabelEncoder()

In [8]:
y = gender_encoder.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0])

In [9]:
# SVM is distance based ML algo , we awill apply standard scaler

#from sklearn.preprocessing import StandardScaler

#scaler = StandardScaler()

In [10]:
#X = scaler.fit_transform(X)
X

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
...        ...       ...       ...       ...       ...       ...        ...   
3163  0.131884  0.084734  0.153707  0.049285  0.201144  0.151859   1.762129   
3164  0.116221  0.089221  0.076758  0.042718  0.204911  0.162193   0.693730   
3165  0.142056  0.095798  0.183731  0.033424  0.224360  0.190936   1.876502   
3166  0.143659  0.090628  0.184976  0.043508  0.219943  0.176435   1.591065   
3167  0.165509  0.092884  0.183044  0.070072  0.250827  0.180756   1.705029   

             kurt    sp.ent       sfm      mode  centroid   meanfun    minfun  \
0      274.402906  0.893369  0.491918  0.000000  0.059781  0.084279  0.015702   
1      634.613855  0.892193  0.513724  0.000000  0.066009  0.107937  0.015826   
2     1024.927705  0.846389  0.478905  0.000000  0.077316  0.098706  0.015656   
3        4.177296  0.963322  0.727232  0.083878  0.151228  0.088965  0.017798   
4        4.333713  0.971955  0.783568  0.104261  0.135120  0.106398  0.016931   
...           ...       ...       ...       ...       ...       ...       ...   
3163     6.630383  0.962934  0.763182  0.200836  0.131884  0.182790  0.083770   
3164     2.503954  0.960716  0.709570  0.013683  0.116221  0.188980  0.034409   
3165     6.604509  0.946854  0.654196  0.008006  0.142056  0.209918  0.039506   
3166     5.388298  0.950436  0.675470  0.212202  0.143659  0.172375  0.034483   
3167     5.769115  0.938829  0.601529  0.267702  0.165509  0.185607  0.062257   

        maxfun   meandom    mindom    maxdom   dfrange   modindx  
0     0.275862  0.007812  0.007812  0.007812  0.000000  0.000000  
1     0.250000  0.009014  0.007812  0.054688  0.046875  0.052632  
2     0.271186  0.007990  0.007812  0.015625  0.007812  0.046512  
3     0.250000  0.201497  0.007812  0.562500  0.554688  0.247119  
4     0.266667  0.712812  0.007812  5.484375  5.476562  0.208274  
...        ...       ...       ...       ...       ...       ...  
3163  0.262295  0.832899  0.007812  4.210938  4.203125  0.161929  
3164  0.275862  0.909856  0.039062  3.679688  3.640625  0.277897  
3165  0.275862  0.494271  0.007812  2.937500  2.929688  0.194759  
3166  0.250000  0.791360  0.007812  3.593750  3.585938  0.311002  
3167  0.271186  0.227022  0.007812  0.554688  0.546875  0.350000  

[3168 rows x 20 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state= 123)

# Applying the Suuport vector classifier

In [12]:
from sklearn.svm import SVC
from sklearn import metrics

In [13]:
svc_model = SVC()
svc_model.fit(X_train, y_train)

SVC()

In [14]:
y_pred = svc_model.predict(X_test)

In [15]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [16]:
y_test

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,

# Model Evaluation

In [17]:
accuracy_svm = metrics.accuracy_score(y_test, y_pred)
accuracy_svm

0.6527777777777778

In [18]:
# Lets print the confusion matrix 

print(metrics.confusion_matrix(y_test, y_pred))

[[200 200]
 [ 75 317]]


In [19]:
# Lets see if my model is overfitted

y_pred_train = svc_model.predict(X_train)
print(metrics.accuracy_score(y_train, y_pred_train))

0.6813973063973064


# lets do the hyperparameter tuning

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
param_grid = {'C':[.1,1,10, 100], 'gamma': [100, 10, 1, .1, .01, .001 ]}

In [22]:
param_grid

{'C': [0.1, 1, 10, 100], 'gamma': [100, 10, 1, 0.1, 0.01, 0.001]}

In [23]:
grid = GridSearchCV(SVC(), param_grid, refit= True, verbose = 2)

In [24]:
grid

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [100, 10, 1, 0.1, 0.01, 0.001]},
             verbose=2)

In [25]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] END ...................................C=0.1, gamma=100; total time=   1.1s
[CV] END ...................................C=0.1, gamma=100; total time=   1.1s
[CV] END ...................................C=0.1, gamma=100; total time=   0.9s
[CV] END ...................................C=0.1, gamma=100; total time=   1.1s
[CV] END ...................................C=0.1, gamma=100; total time=   1.4s
[CV] END ....................................C=0.1, gamma=10; total time=   1.1s
[CV] END ....................................C=0.1, gamma=10; total time=   0.8s
[CV] END ....................................C=0.1, gamma=10; total time=   0.9s
[CV] END ....................................C=0.1, gamma=10; total time=   0.8s
[CV] END ....................................C=0.1, gamma=10; total time=   0.8s
[CV] END .....................................C=0.1, gamma=1; total time=   0.5s
[CV] END .....................................C

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [100, 10, 1, 0.1, 0.01, 0.001]},
             verbose=2)

In [26]:
grid_prediction = grid.predict(X_test)

In [27]:
grid_prediction

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,

In [28]:
print(metrics.accuracy_score(y_test,grid_prediction))

0.9040404040404041


In [29]:
grid.best_params_

{'C': 100, 'gamma': 0.01}

In [30]:
# Lets create the final model with the help of the final and best parameters found ot in the Gridsearch CV

In [31]:
svc_grid_model = SVC(C=1.0 , gamma = 0.1)

In [32]:
svc_grid_model

SVC(gamma=0.1)

In [33]:
svc_grid_model.fit(X_train , y_train)

SVC(gamma=0.1)

In [34]:
y_grid_pred = svc_grid_model.predict(X_test)
y_grid_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,

In [35]:
print(metrics.accuracy_score(y_test , y_grid_pred))

0.7133838383838383


# Lets apply PCA to see the impact

In [36]:
from sklearn.decomposition import PCA

In [37]:
# Creating a variable name to import PCA values

sklearn_pca = PCA(n_components= 5)

In [38]:
X # Original Data
print(X.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
dtypes: float64(20)
memory usage: 4

In [39]:
X_pca= sklearn_pca.fit_transform(X)

In [40]:
X_pca

array([[ 2.38081294e+02, -4.80224677e+00, -2.24803910e+00,
         1.22248149e-01,  1.23979648e-01],
       [ 5.98396593e+02, -1.02137403e+00, -8.81787888e-01,
         2.11010072e-02,  8.25205909e-02],
       [ 9.88762667e+02,  3.02260542e+00,  2.62021449e+00,
        -4.77090700e-02, -1.22630225e-01],
       ...,
       [-2.99567425e+01, -3.26518493e+00,  4.68605195e-01,
         1.51466971e-01,  2.12384259e-01],
       [-3.11908741e+01, -2.32061968e+00,  6.91941205e-01,
        -7.39357446e-02,  2.43409389e-01],
       [-3.07626982e+01, -6.64483239e+00,  7.32112467e-01,
         1.03080636e-01,  4.41422937e-02]])

In [41]:
X_pca = pd.DataFrame(X_pca, columns= ["PC1","PC2","PC3","PC4","PC5"])
#X_pca.columns= ["PC1","PC2","PC3","PC4","PC5"]
X_pca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   PC1     3168 non-null   float64
 1   PC2     3168 non-null   float64
 2   PC3     3168 non-null   float64
 3   PC4     3168 non-null   float64
 4   PC5     3168 non-null   float64
dtypes: float64(5)
memory usage: 123.9 KB


In [42]:
X

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
...        ...       ...       ...       ...       ...       ...        ...   
3163  0.131884  0.084734  0.153707  0.049285  0.201144  0.151859   1.762129   
3164  0.116221  0.089221  0.076758  0.042718  0.204911  0.162193   0.693730   
3165  0.142056  0.095798  0.183731  0.033424  0.224360  0.190936   1.876502   
3166  0.143659  0.090628  0.184976  0.043508  0.219943  0.176435   1.591065   
3167  0.165509  0.092884  0.183044  0.070072  0.250827  0.180756   1.705029   

             kurt    sp.ent       sfm      mode  centroid   meanfun    minfun  \
0      274.402906  0.893369  0.491918  0.000000  0.059781  0.084279  0.015702   
1      634.613855  0.892193  0.513724  0.000000  0.066009  0.107937  0.015826   
2     1024.927705  0.846389  0.478905  0.000000  0.077316  0.098706  0.015656   
3        4.177296  0.963322  0.727232  0.083878  0.151228  0.088965  0.017798   
4        4.333713  0.971955  0.783568  0.104261  0.135120  0.106398  0.016931   
...           ...       ...       ...       ...       ...       ...       ...   
3163     6.630383  0.962934  0.763182  0.200836  0.131884  0.182790  0.083770   
3164     2.503954  0.960716  0.709570  0.013683  0.116221  0.188980  0.034409   
3165     6.604509  0.946854  0.654196  0.008006  0.142056  0.209918  0.039506   
3166     5.388298  0.950436  0.675470  0.212202  0.143659  0.172375  0.034483   
3167     5.769115  0.938829  0.601529  0.267702  0.165509  0.185607  0.062257   

        maxfun   meandom    mindom    maxdom   dfrange   modindx  
0     0.275862  0.007812  0.007812  0.007812  0.000000  0.000000  
1     0.250000  0.009014  0.007812  0.054688  0.046875  0.052632  
2     0.271186  0.007990  0.007812  0.015625  0.007812  0.046512  
3     0.250000  0.201497  0.007812  0.562500  0.554688  0.247119  
4     0.266667  0.712812  0.007812  5.484375  5.476562  0.208274  
...        ...       ...       ...       ...       ...       ...  
3163  0.262295  0.832899  0.007812  4.210938  4.203125  0.161929  
3164  0.275862  0.909856  0.039062  3.679688  3.640625  0.277897  
3165  0.275862  0.494271  0.007812  2.937500  2.929688  0.194759  
3166  0.250000  0.791360  0.007812  3.593750  3.585938  0.311002  
3167  0.271186  0.227022  0.007812  0.554688  0.546875  0.350000  

[3168 rows x 20 columns]

In [43]:
X_pca

PC1       PC2       PC3       PC4       PC5
0     238.081294 -4.802247 -2.248039  0.122248  0.123980
1     598.396593 -1.021374 -0.881788  0.021101  0.082521
2     988.762667  3.022605  2.620214 -0.047709 -0.122630
3     -32.368181 -6.639116  1.157241  0.175888  0.156797
4     -32.286811  0.339167  1.048950  0.264576  0.341542
...          ...       ...       ...       ...       ...
3163  -29.953017 -1.439902  0.531723 -0.019032  0.330378
3164  -34.102331 -2.214047  1.498090 -0.143124  0.296095
3165  -29.956743 -3.265185  0.468605  0.151467  0.212384
3166  -31.190874 -2.320620  0.691941 -0.073936  0.243409
3167  -30.762698 -6.644832  0.732112  0.103081  0.044142

[3168 rows x 5 columns]

In [44]:
print(X_pca.shape)

(3168, 5)


In [45]:
X_pca

PC1       PC2       PC3       PC4       PC5
0     238.081294 -4.802247 -2.248039  0.122248  0.123980
1     598.396593 -1.021374 -0.881788  0.021101  0.082521
2     988.762667  3.022605  2.620214 -0.047709 -0.122630
3     -32.368181 -6.639116  1.157241  0.175888  0.156797
4     -32.286811  0.339167  1.048950  0.264576  0.341542
...          ...       ...       ...       ...       ...
3163  -29.953017 -1.439902  0.531723 -0.019032  0.330378
3164  -34.102331 -2.214047  1.498090 -0.143124  0.296095
3165  -29.956743 -3.265185  0.468605  0.151467  0.212384
3166  -31.190874 -2.320620  0.691941 -0.073936  0.243409
3167  -30.762698 -6.644832  0.732112  0.103081  0.044142

[3168 rows x 5 columns]

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X_pca,y, random_state= 123)

X_train

PC1       PC2       PC3       PC4       PC5
2795 -25.372793  5.768895 -0.479744 -0.325991  0.024354
2881 -25.306568  0.003521 -0.547053 -0.021158 -0.153792
2209 -29.575722 -0.066108  0.326864 -0.144565  0.144799
2681 -26.829848  4.112275 -0.099039  0.197686 -0.107265
3066  14.018306 -2.148791 -2.320251  0.307542  0.078576
...         ...       ...       ...       ...       ...
2154 -23.841457  1.815795 -0.718223  0.125292 -0.181616
3089   6.460304 -6.777220 -2.054570 -0.010783 -0.012699
1766 -12.322514  1.480578 -1.271272  0.097431 -0.021980
1122 -33.776331  5.227721  1.071335  0.046162  0.094261
1346 -31.775375 -1.104191  0.757969 -0.143260  0.001174

[2376 rows x 5 columns]

In [47]:
svc_model_pca = SVC()

svc_model_pca.fit(X_train, y_train)

SVC()

In [48]:
y_pred_pca = svc_model_pca.predict(X_test)

In [49]:
print(metrics.accuracy_score(y_test,y_pred_pca))

0.6565656565656566


In [50]:
print("The accucrcy Score of orginal SVM is :", metrics.accuracy_score(y_test,y_pred))
print("The accucrcy Score of PCA SVM is :", metrics.accuracy_score(y_test,y_pred_pca))

The accucrcy Score of orginal SVM is : 0.6527777777777778
The accucrcy Score of PCA SVM is : 0.6565656565656566
